---
# DuckDB CLI installation

- name: Download and install DuckDB CLI
  ansible.builtin.unarchive:
    src: https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip
    dest: /usr/local/bin
    remote_src: true
    mode: '0755'
